In [ ]:
# BUILDING LOGISTIC REGRESSION FROM SCRATCH

In [49]:
import pandas as pd
!pip install numpy
import numpy as np

Requirement already satisfied: numpy in c:\java\envs\tensorflow\lib\site-packages (1.19.5)

In [5]:
!pip3 install -U scikit-learn scipy matplotlib
from sklearn.preprocessing import StandardScaler

Collecting scikit-learn
  Using cached scikit_learn-1.0.2-cp39-cp39-win_amd64.whl (7.2 MB)
Requirement already satisfied: scipy in c:\java\envs\tensorflow\lib\site-packages (1.7.3)
Collecting scipy
  Downloading scipy-1.8.0-cp39-cp39-win_amd64.whl (36.9 MB)
Requirement already satisfied: matplotlib in c:\java\envs\tensorflow\lib\site-packages (3.5.1)
Requirement already satisfied: numpy>=1.14.6 in c:\java\envs\tensorflow\lib\site-packages (from scikit-learn) (1.19.5)
Collecting joblib>=0.11
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: packaging>=20.0 in c:\java\envs\tensorflow\lib\site-packages (from matplotlib) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in c:\java\envs\tensorflow\lib\site-packages (from matplotlib) (3.0.4)
Requirement already satisfied: pillow>=6.2.0 in c:\java\envs\tensorflow\lib\site-packages (from matplotlib) (9.0.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\java\envs\tensorflow\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\java\envs\tensorflow\lib\site-packages (from matplotlib) (4.28.5)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\java\envs\tensorflow\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\java\envs\tensorflow\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: six>=1.5 in c:\java\envs\tensorflow\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
  Attempting uninstall: scipy
    Found existing installation: scipy 1.7.3
    Uninstalling scipy-1.7.3:
      Successfully uninstalled scipy-1.7.3
Successfully installed joblib-1.1.0 scikit-learn-1.0.2 scipy-1.8.0 threadpoolctl-3.1.0

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import os

In [19]:
diabetes_dataset = pd.read_csv('C:\\Users\kal ab\Desktop\ML\\diabetes_binary_5050split_health_indicators_BRFSS2015.csv')

In [20]:
diabetes_dataset.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

In [21]:
diabetes_dataset.shape

(70692, 22)

In [22]:
diabetes_dataset.describe()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,...,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000
mean,0.500000,0.563458,0.525703,0.975259,29.856985,0.475273,0.062171,0.147810,0.703036,0.611795,...,0.954960,0.093914,2.837082,3.752037,5.810417,0.252730,0.456997,8.584055,4.920953,5.698311
std,0.500004,0.495960,0.499342,0.155336,7.113954,0.499392,0.241468,0.354914,0.456924,0.487345,...,0.207394,0.291712,1.113565,8.155627,10.062261,0.434581,0.498151,2.852153,1.029081,2.175196
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,7.000000,4.000000,4.000000
50%,0.500000,1.000000,1.000000,1.000000,29.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,9.000000,5.000000,6.000000
75%,1.000000,1.000000,1.000000,1.000000,33.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,4.000000,2.000000,6.000000,1.000000,1.000000,11.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [25]:
diabetes_dataset['Diabetes_binary'].value_counts()

0.0    35346
1.0    35346
Name: Diabetes_binary, dtype: int64

In [27]:
diabetes_dataset.groupby('Diabetes_binary').mean()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
Diabetes_binary,,,,,,,,,,,,,,,,,,,,,
0.0,0.374243,0.381288,0.957336,27.769960,0.432326,0.031885,0.072738,0.775533,0.638149,0.821140,...,0.950150,0.081961,2.383183,3.042268,3.666355,0.134244,0.434872,7.789057,5.096390,6.186527
1.0,0.752674,0.670118,0.993182,31.944011,0.518220,0.092457,0.222882,0.630538,0.585441,0.756408,...,0.959769,0.105868,3.290981,4.461806,7.954479,0.371216,0.479121,9.379053,4.745516,5.210094

In [28]:
features = diabetes_dataset.drop(columns = 'Diabetes_binary', axis=1)
target = diabetes_dataset['Diabetes_binary']

In [29]:
print(features)

       HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0         1.0       0.0        1.0  26.0     0.0     0.0
1         1.0       1.0        1.0  26.0     1.0     1.0
2         0.0       0.0        1.0  26.0     0.0     0.0
3         1.0       1.0        1.0  28.0     1.0     0.0
4         0.0       0.0        1.0  29.0     1.0     0.0
...       ...       ...        ...   ...     ...     ...
70687     0.0       1.0        1.0  37.0     0.0     0.0
70688     0.0       1.0        1.0  29.0     1.0     0.0
70689     1.0       1.0        1.0  25.0     0.0     0.0
70690     1.0       1.0        1.0  18.0     0.0     0.0
70691     1.0       1.0        1.0  25.0     0.0     0.0

       HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
0                       0.0           1.0     0.0      1.0  ...
1                       0.0           0.0     1.0      0.0  ...
2                       0.0           1.0     1.0      1.0  ...
3                       0.0           1.0     1.0      1.0  ...
4                       0.0           1.0     1.0      1.0  ...
...                     ...           ...     ...      ...  ...
70687                   0.0           0.0     0.0      1.0  ...
70688                   1.0           0.0     1.0      1.0  ...
70689                   1.0           0.0     1.0      0.0  ...
70690                   0.0           0.0     0.0      0.0  ...
70691                   1.0           1.0     1.0      0.0  ...

       AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  \
0                1.0          0.0      3.0       5.0      30.0       0.0  1.0
1                1.0          0.0      3.0       0.0       0.0       0.0  1.0
2                1.0          0.0      1.0       0.0      10.0       0.0  1.0
3                1.0          0.0      3.0       0.0       3.0       0.0  1.0
4                1.0          0.0      2.0       0.0       0.0       0.0  0.0
...              ...          ...      ...       ...       ...       ...  ...
70687            1.0          0.0      4.0       0.0       0.0       0.0  0.0
70688            1.0          0.0      2.0       0.0       0.0       1.0  1.0
70689            1.0          0.0      5.0      15.0       0.0       1.0  0.0
70690            1.0          0.0      4.0       0.0       0.0       1.0  0.0
70691            1.0          0.0      2.0       0.0       0.0       0.0  0.0

        Age  Education  Income
0       4.0        6.0     8.0
1      12.0        6.0     8.0
2      13.0        6.0     8.0
3      11.0        6.0     8.0
4       8.0        5.0     8.0
...     ...        ...     ...
70687   6.0        4.0     1.0
70688  10.0        3.0     6.0
70689  13.0        6.0     4.0
70690  11.0        2.0     4.0
70691   9.0        6.0     2.0

[70692 rows x 21 columns]

In [30]:
print(target)

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
70687    1.0
70688    1.0
70689    1.0
70690    1.0
70691    1.0
Name: Diabetes_binary, Length: 70692, dtype: float64

In [34]:
scaler=StandardScaler()
features=scaler.fit_transform(features)

In [33]:
scaler.fit(features)

StandardScaler()

In [38]:
X_train, X_test, Y_train,Y_test = train_test_split(features,target, test_size = 0.2, random_state=2)

In [36]:
print(features.shape, X_train.shape, X_test.shape)

(70692, 21) (56553, 21) (14139, 21)

In [ ]:
#

In [70]:
class Logistic_Regression():


  # declaring learning rate & number of iterations (Hyperparametes)
  def __init__(self, learning_rate, no_of_iterations):

    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations



  # fit function to train the model with dataset
  def fit(self, X, Y):

    # number of data points in the dataset (number of rows)  -->  m
    # number of input features in the dataset (number of columns)  --> n
    self.m, self.n = X.shape


    #initiating weight & bias value

    self.w = np.zeros(self.n)
    
    self.b = 0

    self.X = X

    self.Y = Y


    # implementing Gradient Descent for Optimization

    for i in range(self.no_of_iterations):     
      self.update_weights()



  def update_weights(self):

    # Y_hat formula (sigmoid function)

    Y_hat = 1 / (1 + np.exp( - (self.X.dot(self.w) + self.b ) ))    


    # derivaties

    dw = (1/self.m)*np.dot(self.X.T, (Y_hat - self.Y))

    db = (1/self.m)*np.sum(Y_hat - self.Y)


    # updating the weights & bias using gradient descent

    self.w = self.w - self.learning_rate * dw

    self.b = self.b - self.learning_rate * db


  # Sigmoid Equation & Decision Boundary

  def predict(self, X):

    Y_pred = 1 / (1 + np.exp( - (X.dot(self.w) + self.b ) ))     
    Y_pred = np.where( Y_pred > 0.5, 1, 0)
    return Y_pred

In [73]:
Model = Logistic_Regression(learning_rate=0.003, no_of_iterations=100000)

In [74]:
Model.fit(X_train, Y_train)

In [75]:
X_train_prediction = Model.predict(X_train)
training_data_accuracy = accuracy_score( Y_train, X_train_prediction)

In [76]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.7408979187664668

In [78]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score( Y_test, X_test_prediction)

In [79]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.741353702524931

In [83]:
input_data = (1.0,1.0,1.0,32.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,10.0,6.0,8.0)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[[ 0.88020109  0.94984976  0.15927581  0.30124316  1.05073965 -0.25747348
  -0.41647033 -1.53863842  0.79657699  0.51748481 -0.21125109  0.21717454
  -0.32194493  0.1463042  -0.46005828 -0.57745057 -0.58155367  1.09004602
   0.49645134  1.04856175  1.05815996]]
[0]
The person is not diabetic

C:\java\envs\tensorflow\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(